### ISSUE TITLE
HOLA... alguna idea de como conectar WhatsAPP Web a mysql es decir que los mensaje se guarden hay  ?

### ISSUE THREAD

**Issue by Albert947** [ABitOfSquad/WhatsappMysql#1]
QUIERO GESTIONAR SOLICITUDES MEDIANTE WHATSAPP WEB ES DECIR QUE ME LLEGUEN LOS MENSAJES Y ELLOS SE VAYAN A LA BASE DE DATOS EN MYSQL Y DESPUÉS CON UNA INTERFAZ GESTIONAR LAS PETICIONES

**Comment by Nickforall** [comment]
HELLO, THIS PROJECT IS UNMAINTAINED AS YOU MIGHT HAVE NOTICED. YOU SHOULD ALSO NOTICE THAT NOT EVERYONE SPEAKS SPANISH, AND WRITING IN CAPS DOESN'T MAKE YOU MORE UNDERSTANDABLE.

Anyways, from the magic of google translate I understand that you want to dump all messages from whatsapp web in mysql. This project is not for that. It parsed messages from an export of group chats into a mysql format.

Closing this now.
